// Code generated by ent, DO NOT EDIT.

package chart

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the chart type in the database.
	Label = "chart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGoal holds the string denoting the goal field in the database.
	FieldGoal = "goal"
	// FieldChartData holds the string denoting the chart_data field in the database.
	FieldChartData = "chart_data"
	// FieldChartType holds the string denoting the chart_type field in the database.
	FieldChartType = "chart_type"
	// FieldGenChart holds the string denoting the gen_chart field in the database.
	FieldGenChart = "gen_chart"
	// FieldGenResult holds the string denoting the gen_result field in the database.
	FieldGenResult = "gen_result"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExecMessage holds the string denoting the exec_message field in the database.
	FieldExecMessage = "exec_message"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the chart in the database.
	Table = "charts"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "charts"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
)

// Columns holds all SQL columns for chart fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldGoal,
	FieldChartData,
	FieldChartType,
	FieldGenChart,
	FieldGenResult,
	FieldStatus,
	FieldExecMessage,
	FieldUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ChartTypeValidator is a validator for the "chart_type" field. It is called by the builders before save.
	ChartTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the Chart queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGoal orders the results by the goal field.
func ByGoal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoal, opts...).ToFunc()
}

// ByChartData orders the results by the chart_data field.
func ByChartData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChartData, opts...).ToFunc()
}

// ByChartType orders the results by the chart_type field.
func ByChartType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChartType, opts...).ToFunc()
}

// ByGenChart orders the results by the gen_chart field.
func ByGenChart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenChart, opts...).ToFunc()
}

// ByGenResult orders the results by the gen_result field.
func ByGenResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenResult, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExecMessage orders the results by the exec_message field.
func ByExecMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecMessage, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
