// Code generated by ent, DO NOT EDIT.

package chart

import (
	"time"
	"wood-bi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldName, v))
}

// Goal applies equality check predicate on the "goal" field. It's identical to GoalEQ.
func Goal(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGoal, v))
}

// ChartData applies equality check predicate on the "chart_data" field. It's identical to ChartDataEQ.
func ChartData(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldChartData, v))
}

// ChartType applies equality check predicate on the "chart_type" field. It's identical to ChartTypeEQ.
func ChartType(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldChartType, v))
}

// GenChart applies equality check predicate on the "gen_chart" field. It's identical to GenChartEQ.
func GenChart(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGenChart, v))
}

// GenResult applies equality check predicate on the "gen_result" field. It's identical to GenResultEQ.
func GenResult(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGenResult, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldStatus, v))
}

// ExecMessage applies equality check predicate on the "exec_message" field. It's identical to ExecMessageEQ.
func ExecMessage(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldExecMessage, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldName, v))
}

// GoalEQ applies the EQ predicate on the "goal" field.
func GoalEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGoal, v))
}

// GoalNEQ applies the NEQ predicate on the "goal" field.
func GoalNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldGoal, v))
}

// GoalIn applies the In predicate on the "goal" field.
func GoalIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldGoal, vs...))
}

// GoalNotIn applies the NotIn predicate on the "goal" field.
func GoalNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldGoal, vs...))
}

// GoalGT applies the GT predicate on the "goal" field.
func GoalGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldGoal, v))
}

// GoalGTE applies the GTE predicate on the "goal" field.
func GoalGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldGoal, v))
}

// GoalLT applies the LT predicate on the "goal" field.
func GoalLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldGoal, v))
}

// GoalLTE applies the LTE predicate on the "goal" field.
func GoalLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldGoal, v))
}

// GoalContains applies the Contains predicate on the "goal" field.
func GoalContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldGoal, v))
}

// GoalHasPrefix applies the HasPrefix predicate on the "goal" field.
func GoalHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldGoal, v))
}

// GoalHasSuffix applies the HasSuffix predicate on the "goal" field.
func GoalHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldGoal, v))
}

// GoalIsNil applies the IsNil predicate on the "goal" field.
func GoalIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldGoal))
}

// GoalNotNil applies the NotNil predicate on the "goal" field.
func GoalNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldGoal))
}

// GoalEqualFold applies the EqualFold predicate on the "goal" field.
func GoalEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldGoal, v))
}

// GoalContainsFold applies the ContainsFold predicate on the "goal" field.
func GoalContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldGoal, v))
}

// ChartDataEQ applies the EQ predicate on the "chart_data" field.
func ChartDataEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldChartData, v))
}

// ChartDataNEQ applies the NEQ predicate on the "chart_data" field.
func ChartDataNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldChartData, v))
}

// ChartDataIn applies the In predicate on the "chart_data" field.
func ChartDataIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldChartData, vs...))
}

// ChartDataNotIn applies the NotIn predicate on the "chart_data" field.
func ChartDataNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldChartData, vs...))
}

// ChartDataGT applies the GT predicate on the "chart_data" field.
func ChartDataGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldChartData, v))
}

// ChartDataGTE applies the GTE predicate on the "chart_data" field.
func ChartDataGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldChartData, v))
}

// ChartDataLT applies the LT predicate on the "chart_data" field.
func ChartDataLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldChartData, v))
}

// ChartDataLTE applies the LTE predicate on the "chart_data" field.
func ChartDataLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldChartData, v))
}

// ChartDataContains applies the Contains predicate on the "chart_data" field.
func ChartDataContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldChartData, v))
}

// ChartDataHasPrefix applies the HasPrefix predicate on the "chart_data" field.
func ChartDataHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldChartData, v))
}

// ChartDataHasSuffix applies the HasSuffix predicate on the "chart_data" field.
func ChartDataHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldChartData, v))
}

// ChartDataIsNil applies the IsNil predicate on the "chart_data" field.
func ChartDataIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldChartData))
}

// ChartDataNotNil applies the NotNil predicate on the "chart_data" field.
func ChartDataNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldChartData))
}

// ChartDataEqualFold applies the EqualFold predicate on the "chart_data" field.
func ChartDataEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldChartData, v))
}

// ChartDataContainsFold applies the ContainsFold predicate on the "chart_data" field.
func ChartDataContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldChartData, v))
}

// ChartTypeEQ applies the EQ predicate on the "chart_type" field.
func ChartTypeEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldChartType, v))
}

// ChartTypeNEQ applies the NEQ predicate on the "chart_type" field.
func ChartTypeNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldChartType, v))
}

// ChartTypeIn applies the In predicate on the "chart_type" field.
func ChartTypeIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldChartType, vs...))
}

// ChartTypeNotIn applies the NotIn predicate on the "chart_type" field.
func ChartTypeNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldChartType, vs...))
}

// ChartTypeGT applies the GT predicate on the "chart_type" field.
func ChartTypeGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldChartType, v))
}

// ChartTypeGTE applies the GTE predicate on the "chart_type" field.
func ChartTypeGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldChartType, v))
}

// ChartTypeLT applies the LT predicate on the "chart_type" field.
func ChartTypeLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldChartType, v))
}

// ChartTypeLTE applies the LTE predicate on the "chart_type" field.
func ChartTypeLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldChartType, v))
}

// ChartTypeContains applies the Contains predicate on the "chart_type" field.
func ChartTypeContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldChartType, v))
}

// ChartTypeHasPrefix applies the HasPrefix predicate on the "chart_type" field.
func ChartTypeHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldChartType, v))
}

// ChartTypeHasSuffix applies the HasSuffix predicate on the "chart_type" field.
func ChartTypeHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldChartType, v))
}

// ChartTypeIsNil applies the IsNil predicate on the "chart_type" field.
func ChartTypeIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldChartType))
}

// ChartTypeNotNil applies the NotNil predicate on the "chart_type" field.
func ChartTypeNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldChartType))
}

// ChartTypeEqualFold applies the EqualFold predicate on the "chart_type" field.
func ChartTypeEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldChartType, v))
}

// ChartTypeContainsFold applies the ContainsFold predicate on the "chart_type" field.
func ChartTypeContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldChartType, v))
}

// GenChartEQ applies the EQ predicate on the "gen_chart" field.
func GenChartEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGenChart, v))
}

// GenChartNEQ applies the NEQ predicate on the "gen_chart" field.
func GenChartNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldGenChart, v))
}

// GenChartIn applies the In predicate on the "gen_chart" field.
func GenChartIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldGenChart, vs...))
}

// GenChartNotIn applies the NotIn predicate on the "gen_chart" field.
func GenChartNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldGenChart, vs...))
}

// GenChartGT applies the GT predicate on the "gen_chart" field.
func GenChartGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldGenChart, v))
}

// GenChartGTE applies the GTE predicate on the "gen_chart" field.
func GenChartGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldGenChart, v))
}

// GenChartLT applies the LT predicate on the "gen_chart" field.
func GenChartLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldGenChart, v))
}

// GenChartLTE applies the LTE predicate on the "gen_chart" field.
func GenChartLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldGenChart, v))
}

// GenChartContains applies the Contains predicate on the "gen_chart" field.
func GenChartContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldGenChart, v))
}

// GenChartHasPrefix applies the HasPrefix predicate on the "gen_chart" field.
func GenChartHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldGenChart, v))
}

// GenChartHasSuffix applies the HasSuffix predicate on the "gen_chart" field.
func GenChartHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldGenChart, v))
}

// GenChartIsNil applies the IsNil predicate on the "gen_chart" field.
func GenChartIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldGenChart))
}

// GenChartNotNil applies the NotNil predicate on the "gen_chart" field.
func GenChartNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldGenChart))
}

// GenChartEqualFold applies the EqualFold predicate on the "gen_chart" field.
func GenChartEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldGenChart, v))
}

// GenChartContainsFold applies the ContainsFold predicate on the "gen_chart" field.
func GenChartContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldGenChart, v))
}

// GenResultEQ applies the EQ predicate on the "gen_result" field.
func GenResultEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldGenResult, v))
}

// GenResultNEQ applies the NEQ predicate on the "gen_result" field.
func GenResultNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldGenResult, v))
}

// GenResultIn applies the In predicate on the "gen_result" field.
func GenResultIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldGenResult, vs...))
}

// GenResultNotIn applies the NotIn predicate on the "gen_result" field.
func GenResultNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldGenResult, vs...))
}

// GenResultGT applies the GT predicate on the "gen_result" field.
func GenResultGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldGenResult, v))
}

// GenResultGTE applies the GTE predicate on the "gen_result" field.
func GenResultGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldGenResult, v))
}

// GenResultLT applies the LT predicate on the "gen_result" field.
func GenResultLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldGenResult, v))
}

// GenResultLTE applies the LTE predicate on the "gen_result" field.
func GenResultLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldGenResult, v))
}

// GenResultContains applies the Contains predicate on the "gen_result" field.
func GenResultContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldGenResult, v))
}

// GenResultHasPrefix applies the HasPrefix predicate on the "gen_result" field.
func GenResultHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldGenResult, v))
}

// GenResultHasSuffix applies the HasSuffix predicate on the "gen_result" field.
func GenResultHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldGenResult, v))
}

// GenResultIsNil applies the IsNil predicate on the "gen_result" field.
func GenResultIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldGenResult))
}

// GenResultNotNil applies the NotNil predicate on the "gen_result" field.
func GenResultNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldGenResult))
}

// GenResultEqualFold applies the EqualFold predicate on the "gen_result" field.
func GenResultEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldGenResult, v))
}

// GenResultContainsFold applies the ContainsFold predicate on the "gen_result" field.
func GenResultContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldGenResult, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldStatus, v))
}

// ExecMessageEQ applies the EQ predicate on the "exec_message" field.
func ExecMessageEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldExecMessage, v))
}

// ExecMessageNEQ applies the NEQ predicate on the "exec_message" field.
func ExecMessageNEQ(v string) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldExecMessage, v))
}

// ExecMessageIn applies the In predicate on the "exec_message" field.
func ExecMessageIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldExecMessage, vs...))
}

// ExecMessageNotIn applies the NotIn predicate on the "exec_message" field.
func ExecMessageNotIn(vs ...string) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldExecMessage, vs...))
}

// ExecMessageGT applies the GT predicate on the "exec_message" field.
func ExecMessageGT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldExecMessage, v))
}

// ExecMessageGTE applies the GTE predicate on the "exec_message" field.
func ExecMessageGTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldExecMessage, v))
}

// ExecMessageLT applies the LT predicate on the "exec_message" field.
func ExecMessageLT(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldExecMessage, v))
}

// ExecMessageLTE applies the LTE predicate on the "exec_message" field.
func ExecMessageLTE(v string) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldExecMessage, v))
}

// ExecMessageContains applies the Contains predicate on the "exec_message" field.
func ExecMessageContains(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContains(FieldExecMessage, v))
}

// ExecMessageHasPrefix applies the HasPrefix predicate on the "exec_message" field.
func ExecMessageHasPrefix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasPrefix(FieldExecMessage, v))
}

// ExecMessageHasSuffix applies the HasSuffix predicate on the "exec_message" field.
func ExecMessageHasSuffix(v string) predicate.Chart {
	return predicate.Chart(sql.FieldHasSuffix(FieldExecMessage, v))
}

// ExecMessageIsNil applies the IsNil predicate on the "exec_message" field.
func ExecMessageIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldExecMessage))
}

// ExecMessageNotNil applies the NotNil predicate on the "exec_message" field.
func ExecMessageNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldExecMessage))
}

// ExecMessageEqualFold applies the EqualFold predicate on the "exec_message" field.
func ExecMessageEqualFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldEqualFold(FieldExecMessage, v))
}

// ExecMessageContainsFold applies the ContainsFold predicate on the "exec_message" field.
func ExecMessageContainsFold(v string) predicate.Chart {
	return predicate.Chart(sql.FieldContainsFold(FieldExecMessage, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldUserID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Chart {
	return predicate.Chart(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Chart {
	return predicate.Chart(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Chart {
	return predicate.Chart(sql.FieldNotNull(FieldDeletedAt))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Chart {
	return predicate.Chart(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Chart {
	return predicate.Chart(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chart) predicate.Chart {
	return predicate.Chart(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chart) predicate.Chart {
	return predicate.Chart(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chart) predicate.Chart {
	return predicate.Chart(sql.NotPredicates(p))
}
