// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-bi/ent/chart"
	"wood-bi/ent/predicate"
	"wood-bi/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChartUpdate is the builder for updating Chart entities.
type ChartUpdate struct {
	config
	hooks    []Hook
	mutation *ChartMutation
}

// Where appends a list predicates to the ChartUpdate builder.
func (_u *ChartUpdate) Where(ps ...predicate.Chart) *ChartUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ChartUpdate) SetName(v string) *ChartUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableName(v *string) *ChartUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChartUpdate) ClearName() *ChartUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetGoal sets the "goal" field.
func (_u *ChartUpdate) SetGoal(v string) *ChartUpdate {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableGoal(v *string) *ChartUpdate {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// ClearGoal clears the value of the "goal" field.
func (_u *ChartUpdate) ClearGoal() *ChartUpdate {
	_u.mutation.ClearGoal()
	return _u
}

// SetChartData sets the "chart_data" field.
func (_u *ChartUpdate) SetChartData(v string) *ChartUpdate {
	_u.mutation.SetChartData(v)
	return _u
}

// SetNillableChartData sets the "chart_data" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableChartData(v *string) *ChartUpdate {
	if v != nil {
		_u.SetChartData(*v)
	}
	return _u
}

// ClearChartData clears the value of the "chart_data" field.
func (_u *ChartUpdate) ClearChartData() *ChartUpdate {
	_u.mutation.ClearChartData()
	return _u
}

// SetChartType sets the "chart_type" field.
func (_u *ChartUpdate) SetChartType(v string) *ChartUpdate {
	_u.mutation.SetChartType(v)
	return _u
}

// SetNillableChartType sets the "chart_type" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableChartType(v *string) *ChartUpdate {
	if v != nil {
		_u.SetChartType(*v)
	}
	return _u
}

// ClearChartType clears the value of the "chart_type" field.
func (_u *ChartUpdate) ClearChartType() *ChartUpdate {
	_u.mutation.ClearChartType()
	return _u
}

// SetGenChart sets the "gen_chart" field.
func (_u *ChartUpdate) SetGenChart(v string) *ChartUpdate {
	_u.mutation.SetGenChart(v)
	return _u
}

// SetNillableGenChart sets the "gen_chart" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableGenChart(v *string) *ChartUpdate {
	if v != nil {
		_u.SetGenChart(*v)
	}
	return _u
}

// ClearGenChart clears the value of the "gen_chart" field.
func (_u *ChartUpdate) ClearGenChart() *ChartUpdate {
	_u.mutation.ClearGenChart()
	return _u
}

// SetGenResult sets the "gen_result" field.
func (_u *ChartUpdate) SetGenResult(v string) *ChartUpdate {
	_u.mutation.SetGenResult(v)
	return _u
}

// SetNillableGenResult sets the "gen_result" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableGenResult(v *string) *ChartUpdate {
	if v != nil {
		_u.SetGenResult(*v)
	}
	return _u
}

// ClearGenResult clears the value of the "gen_result" field.
func (_u *ChartUpdate) ClearGenResult() *ChartUpdate {
	_u.mutation.ClearGenResult()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChartUpdate) SetStatus(v string) *ChartUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableStatus(v *string) *ChartUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExecMessage sets the "exec_message" field.
func (_u *ChartUpdate) SetExecMessage(v string) *ChartUpdate {
	_u.mutation.SetExecMessage(v)
	return _u
}

// SetNillableExecMessage sets the "exec_message" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableExecMessage(v *string) *ChartUpdate {
	if v != nil {
		_u.SetExecMessage(*v)
	}
	return _u
}

// ClearExecMessage clears the value of the "exec_message" field.
func (_u *ChartUpdate) ClearExecMessage() *ChartUpdate {
	_u.mutation.ClearExecMessage()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChartUpdate) SetUserID(v int64) *ChartUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableUserID(v *int64) *ChartUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChartUpdate) SetUpdatedAt(v time.Time) *ChartUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChartUpdate) SetDeletedAt(v time.Time) *ChartUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableDeletedAt(v *time.Time) *ChartUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChartUpdate) ClearDeletedAt() *ChartUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChartUpdate) SetOwnerID(id int64) *ChartUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChartUpdate) SetOwner(v *User) *ChartUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ChartMutation object of the builder.
func (_u *ChartUpdate) Mutation() *ChartMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChartUpdate) ClearOwner() *ChartUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChartUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChartUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChartUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChartUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChartUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chart.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChartUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := chart.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chart.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChartType(); ok {
		if err := chart.ChartTypeValidator(v); err != nil {
			return &ValidationError{Name: "chart_type", err: fmt.Errorf(`ent: validator failed for field "Chart.chart_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chart.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Chart.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chart.owner"`)
	}
	return nil
}

func (_u *ChartUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chart.Table, chart.Columns, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chart.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(chart.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(chart.FieldGoal, field.TypeString, value)
	}
	if _u.mutation.GoalCleared() {
		_spec.ClearField(chart.FieldGoal, field.TypeString)
	}
	if value, ok := _u.mutation.ChartData(); ok {
		_spec.SetField(chart.FieldChartData, field.TypeString, value)
	}
	if _u.mutation.ChartDataCleared() {
		_spec.ClearField(chart.FieldChartData, field.TypeString)
	}
	if value, ok := _u.mutation.ChartType(); ok {
		_spec.SetField(chart.FieldChartType, field.TypeString, value)
	}
	if _u.mutation.ChartTypeCleared() {
		_spec.ClearField(chart.FieldChartType, field.TypeString)
	}
	if value, ok := _u.mutation.GenChart(); ok {
		_spec.SetField(chart.FieldGenChart, field.TypeString, value)
	}
	if _u.mutation.GenChartCleared() {
		_spec.ClearField(chart.FieldGenChart, field.TypeString)
	}
	if value, ok := _u.mutation.GenResult(); ok {
		_spec.SetField(chart.FieldGenResult, field.TypeString, value)
	}
	if _u.mutation.GenResultCleared() {
		_spec.ClearField(chart.FieldGenResult, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chart.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMessage(); ok {
		_spec.SetField(chart.FieldExecMessage, field.TypeString, value)
	}
	if _u.mutation.ExecMessageCleared() {
		_spec.ClearField(chart.FieldExecMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chart.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chart.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.OwnerTable,
			Columns: []string{chart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.OwnerTable,
			Columns: []string{chart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChartUpdateOne is the builder for updating a single Chart entity.
type ChartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChartMutation
}

// SetName sets the "name" field.
func (_u *ChartUpdateOne) SetName(v string) *ChartUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableName(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChartUpdateOne) ClearName() *ChartUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetGoal sets the "goal" field.
func (_u *ChartUpdateOne) SetGoal(v string) *ChartUpdateOne {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableGoal(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// ClearGoal clears the value of the "goal" field.
func (_u *ChartUpdateOne) ClearGoal() *ChartUpdateOne {
	_u.mutation.ClearGoal()
	return _u
}

// SetChartData sets the "chart_data" field.
func (_u *ChartUpdateOne) SetChartData(v string) *ChartUpdateOne {
	_u.mutation.SetChartData(v)
	return _u
}

// SetNillableChartData sets the "chart_data" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableChartData(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetChartData(*v)
	}
	return _u
}

// ClearChartData clears the value of the "chart_data" field.
func (_u *ChartUpdateOne) ClearChartData() *ChartUpdateOne {
	_u.mutation.ClearChartData()
	return _u
}

// SetChartType sets the "chart_type" field.
func (_u *ChartUpdateOne) SetChartType(v string) *ChartUpdateOne {
	_u.mutation.SetChartType(v)
	return _u
}

// SetNillableChartType sets the "chart_type" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableChartType(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetChartType(*v)
	}
	return _u
}

// ClearChartType clears the value of the "chart_type" field.
func (_u *ChartUpdateOne) ClearChartType() *ChartUpdateOne {
	_u.mutation.ClearChartType()
	return _u
}

// SetGenChart sets the "gen_chart" field.
func (_u *ChartUpdateOne) SetGenChart(v string) *ChartUpdateOne {
	_u.mutation.SetGenChart(v)
	return _u
}

// SetNillableGenChart sets the "gen_chart" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableGenChart(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetGenChart(*v)
	}
	return _u
}

// ClearGenChart clears the value of the "gen_chart" field.
func (_u *ChartUpdateOne) ClearGenChart() *ChartUpdateOne {
	_u.mutation.ClearGenChart()
	return _u
}

// SetGenResult sets the "gen_result" field.
func (_u *ChartUpdateOne) SetGenResult(v string) *ChartUpdateOne {
	_u.mutation.SetGenResult(v)
	return _u
}

// SetNillableGenResult sets the "gen_result" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableGenResult(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetGenResult(*v)
	}
	return _u
}

// ClearGenResult clears the value of the "gen_result" field.
func (_u *ChartUpdateOne) ClearGenResult() *ChartUpdateOne {
	_u.mutation.ClearGenResult()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChartUpdateOne) SetStatus(v string) *ChartUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableStatus(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExecMessage sets the "exec_message" field.
func (_u *ChartUpdateOne) SetExecMessage(v string) *ChartUpdateOne {
	_u.mutation.SetExecMessage(v)
	return _u
}

// SetNillableExecMessage sets the "exec_message" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableExecMessage(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetExecMessage(*v)
	}
	return _u
}

// ClearExecMessage clears the value of the "exec_message" field.
func (_u *ChartUpdateOne) ClearExecMessage() *ChartUpdateOne {
	_u.mutation.ClearExecMessage()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChartUpdateOne) SetUserID(v int64) *ChartUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableUserID(v *int64) *ChartUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChartUpdateOne) SetUpdatedAt(v time.Time) *ChartUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChartUpdateOne) SetDeletedAt(v time.Time) *ChartUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableDeletedAt(v *time.Time) *ChartUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChartUpdateOne) ClearDeletedAt() *ChartUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChartUpdateOne) SetOwnerID(id int64) *ChartUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChartUpdateOne) SetOwner(v *User) *ChartUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ChartMutation object of the builder.
func (_u *ChartUpdateOne) Mutation() *ChartMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChartUpdateOne) ClearOwner() *ChartUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ChartUpdate builder.
func (_u *ChartUpdateOne) Where(ps ...predicate.Chart) *ChartUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChartUpdateOne) Select(field string, fields ...string) *ChartUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chart entity.
func (_u *ChartUpdateOne) Save(ctx context.Context) (*Chart, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChartUpdateOne) SaveX(ctx context.Context) *Chart {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChartUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChartUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChartUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chart.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChartUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := chart.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chart.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChartType(); ok {
		if err := chart.ChartTypeValidator(v); err != nil {
			return &ValidationError{Name: "chart_type", err: fmt.Errorf(`ent: validator failed for field "Chart.chart_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chart.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Chart.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chart.owner"`)
	}
	return nil
}

func (_u *ChartUpdateOne) sqlSave(ctx context.Context) (_node *Chart, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chart.Table, chart.Columns, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chart.FieldID)
		for _, f := range fields {
			if !chart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chart.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(chart.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(chart.FieldGoal, field.TypeString, value)
	}
	if _u.mutation.GoalCleared() {
		_spec.ClearField(chart.FieldGoal, field.TypeString)
	}
	if value, ok := _u.mutation.ChartData(); ok {
		_spec.SetField(chart.FieldChartData, field.TypeString, value)
	}
	if _u.mutation.ChartDataCleared() {
		_spec.ClearField(chart.FieldChartData, field.TypeString)
	}
	if value, ok := _u.mutation.ChartType(); ok {
		_spec.SetField(chart.FieldChartType, field.TypeString, value)
	}
	if _u.mutation.ChartTypeCleared() {
		_spec.ClearField(chart.FieldChartType, field.TypeString)
	}
	if value, ok := _u.mutation.GenChart(); ok {
		_spec.SetField(chart.FieldGenChart, field.TypeString, value)
	}
	if _u.mutation.GenChartCleared() {
		_spec.ClearField(chart.FieldGenChart, field.TypeString)
	}
	if value, ok := _u.mutation.GenResult(); ok {
		_spec.SetField(chart.FieldGenResult, field.TypeString, value)
	}
	if _u.mutation.GenResultCleared() {
		_spec.ClearField(chart.FieldGenResult, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chart.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMessage(); ok {
		_spec.SetField(chart.FieldExecMessage, field.TypeString, value)
	}
	if _u.mutation.ExecMessageCleared() {
		_spec.ClearField(chart.FieldExecMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chart.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chart.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.OwnerTable,
			Columns: []string{chart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.OwnerTable,
			Columns: []string{chart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chart{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
