// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wood-bi/ent/chart"
	"wood-bi/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Chart is the model entity for the Chart schema.
type Chart struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 图表名称
	Name *string `json:"name,omitempty"`
	// 分析目标
	Goal *string `json:"goal,omitempty"`
	// 原始 CSV 数据
	ChartData *string `json:"chart_data,omitempty"`
	// 图表类型
	ChartType *string `json:"chart_type,omitempty"`
	// AI 生成的 ECharts option JSON
	GenChart *string `json:"gen_chart,omitempty"`
	// AI 分析结论
	GenResult *string `json:"gen_result,omitempty"`
	// wait / running / succeed / failed
	Status string `json:"status,omitempty"`
	// 执行信息（失败原因等）
	ExecMessage *string `json:"exec_message,omitempty"`
	// 创建用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChartQuery when eager-loading is set.
	Edges        ChartEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChartEdges holds the relations/edges for other nodes in the graph.
type ChartEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChartEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chart) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chart.FieldID, chart.FieldUserID:
			values[i] = new(sql.NullInt64)
		case chart.FieldName, chart.FieldGoal, chart.FieldChartData, chart.FieldChartType, chart.FieldGenChart, chart.FieldGenResult, chart.FieldStatus, chart.FieldExecMessage:
			values[i] = new(sql.NullString)
		case chart.FieldCreatedAt, chart.FieldUpdatedAt, chart.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chart fields.
func (_m *Chart) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chart.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case chart.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case chart.FieldGoal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal", values[i])
			} else if value.Valid {
				_m.Goal = new(string)
				*_m.Goal = value.String
			}
		case chart.FieldChartData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chart_data", values[i])
			} else if value.Valid {
				_m.ChartData = new(string)
				*_m.ChartData = value.String
			}
		case chart.FieldChartType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chart_type", values[i])
			} else if value.Valid {
				_m.ChartType = new(string)
				*_m.ChartType = value.String
			}
		case chart.FieldGenChart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gen_chart", values[i])
			} else if value.Valid {
				_m.GenChart = new(string)
				*_m.GenChart = value.String
			}
		case chart.FieldGenResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gen_result", values[i])
			} else if value.Valid {
				_m.GenResult = new(string)
				*_m.GenResult = value.String
			}
		case chart.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case chart.FieldExecMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exec_message", values[i])
			} else if value.Valid {
				_m.ExecMessage = new(string)
				*_m.ExecMessage = value.String
			}
		case chart.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case chart.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chart.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chart.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Chart.
// This includes values selected through modifiers, order, etc.
func (_m *Chart) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Chart entity.
func (_m *Chart) QueryOwner() *UserQuery {
	return NewChartClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this Chart.
// Note that you need to call Chart.Unwrap() before calling this method if this Chart
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Chart) Update() *ChartUpdateOne {
	return NewChartClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Chart entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Chart) Unwrap() *Chart {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chart is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Chart) String() string {
	var builder strings.Builder
	builder.WriteString("Chart(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Goal; v != nil {
		builder.WriteString("goal=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChartData; v != nil {
		builder.WriteString("chart_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChartType; v != nil {
		builder.WriteString("chart_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GenChart; v != nil {
		builder.WriteString("gen_chart=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GenResult; v != nil {
		builder.WriteString("gen_result=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ExecMessage; v != nil {
		builder.WriteString("exec_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Charts is a parsable slice of Chart.
type Charts []*Chart
