// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-bi/ent/chart"
	"wood-bi/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChartCreate is the builder for creating a Chart entity.
type ChartCreate struct {
	config
	mutation *ChartMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ChartCreate) SetName(v string) *ChartCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ChartCreate) SetNillableName(v *string) *ChartCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetGoal sets the "goal" field.
func (_c *ChartCreate) SetGoal(v string) *ChartCreate {
	_c.mutation.SetGoal(v)
	return _c
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_c *ChartCreate) SetNillableGoal(v *string) *ChartCreate {
	if v != nil {
		_c.SetGoal(*v)
	}
	return _c
}

// SetChartData sets the "chart_data" field.
func (_c *ChartCreate) SetChartData(v string) *ChartCreate {
	_c.mutation.SetChartData(v)
	return _c
}

// SetNillableChartData sets the "chart_data" field if the given value is not nil.
func (_c *ChartCreate) SetNillableChartData(v *string) *ChartCreate {
	if v != nil {
		_c.SetChartData(*v)
	}
	return _c
}

// SetChartType sets the "chart_type" field.
func (_c *ChartCreate) SetChartType(v string) *ChartCreate {
	_c.mutation.SetChartType(v)
	return _c
}

// SetNillableChartType sets the "chart_type" field if the given value is not nil.
func (_c *ChartCreate) SetNillableChartType(v *string) *ChartCreate {
	if v != nil {
		_c.SetChartType(*v)
	}
	return _c
}

// SetGenChart sets the "gen_chart" field.
func (_c *ChartCreate) SetGenChart(v string) *ChartCreate {
	_c.mutation.SetGenChart(v)
	return _c
}

// SetNillableGenChart sets the "gen_chart" field if the given value is not nil.
func (_c *ChartCreate) SetNillableGenChart(v *string) *ChartCreate {
	if v != nil {
		_c.SetGenChart(*v)
	}
	return _c
}

// SetGenResult sets the "gen_result" field.
func (_c *ChartCreate) SetGenResult(v string) *ChartCreate {
	_c.mutation.SetGenResult(v)
	return _c
}

// SetNillableGenResult sets the "gen_result" field if the given value is not nil.
func (_c *ChartCreate) SetNillableGenResult(v *string) *ChartCreate {
	if v != nil {
		_c.SetGenResult(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChartCreate) SetStatus(v string) *ChartCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChartCreate) SetNillableStatus(v *string) *ChartCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExecMessage sets the "exec_message" field.
func (_c *ChartCreate) SetExecMessage(v string) *ChartCreate {
	_c.mutation.SetExecMessage(v)
	return _c
}

// SetNillableExecMessage sets the "exec_message" field if the given value is not nil.
func (_c *ChartCreate) SetNillableExecMessage(v *string) *ChartCreate {
	if v != nil {
		_c.SetExecMessage(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChartCreate) SetUserID(v int64) *ChartCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChartCreate) SetCreatedAt(v time.Time) *ChartCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChartCreate) SetNillableCreatedAt(v *time.Time) *ChartCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChartCreate) SetUpdatedAt(v time.Time) *ChartCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChartCreate) SetNillableUpdatedAt(v *time.Time) *ChartCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChartCreate) SetDeletedAt(v time.Time) *ChartCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChartCreate) SetNillableDeletedAt(v *time.Time) *ChartCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChartCreate) SetID(v int64) *ChartCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ChartCreate) SetOwnerID(id int64) *ChartCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ChartCreate) SetOwner(v *User) *ChartCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the ChartMutation object of the builder.
func (_c *ChartCreate) Mutation() *ChartMutation {
	return _c.mutation
}

// Save creates the Chart in the database.
func (_c *ChartCreate) Save(ctx context.Context) (*Chart, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChartCreate) SaveX(ctx context.Context) *Chart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChartCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChartCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChartCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := chart.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chart.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chart.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChartCreate) check() error {
	if v, ok := _c.mutation.Name(); ok {
		if err := chart.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chart.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ChartType(); ok {
		if err := chart.ChartTypeValidator(v); err != nil {
			return &ValidationError{Name: "chart_type", err: fmt.Errorf(`ent: validator failed for field "Chart.chart_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Chart.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chart.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Chart.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Chart.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chart.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chart.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := chart.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Chart.id": %w`, err)}
		}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Chart.owner"`)}
	}
	return nil
}

func (_c *ChartCreate) sqlSave(ctx context.Context) (*Chart, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChartCreate) createSpec() (*Chart, *sqlgraph.CreateSpec) {
	var (
		_node = &Chart{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chart.Table, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chart.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Goal(); ok {
		_spec.SetField(chart.FieldGoal, field.TypeString, value)
		_node.Goal = &value
	}
	if value, ok := _c.mutation.ChartData(); ok {
		_spec.SetField(chart.FieldChartData, field.TypeString, value)
		_node.ChartData = &value
	}
	if value, ok := _c.mutation.ChartType(); ok {
		_spec.SetField(chart.FieldChartType, field.TypeString, value)
		_node.ChartType = &value
	}
	if value, ok := _c.mutation.GenChart(); ok {
		_spec.SetField(chart.FieldGenChart, field.TypeString, value)
		_node.GenChart = &value
	}
	if value, ok := _c.mutation.GenResult(); ok {
		_spec.SetField(chart.FieldGenResult, field.TypeString, value)
		_node.GenResult = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chart.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExecMessage(); ok {
		_spec.SetField(chart.FieldExecMessage, field.TypeString, value)
		_node.ExecMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chart.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(chart.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.OwnerTable,
			Columns: []string{chart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChartCreateBulk is the builder for creating many Chart entities in bulk.
type ChartCreateBulk struct {
	config
	err      error
	builders []*ChartCreate
}

// Save creates the Chart entities in the database.
func (_c *ChartCreateBulk) Save(ctx context.Context) ([]*Chart, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chart, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChartCreateBulk) SaveX(ctx context.Context) []*Chart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChartCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChartCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
