// Code generated by ent, DO NOT EDIT.

package ent

import (
	"wood-bi/ent/placeholder"
	"wood-bi/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	placeholderFields := schema.Placeholder{}.Fields()
	_ = placeholderFields
	// placeholderDescID is the schema descriptor for id field.
	placeholderDescID := placeholderFields[0].Descriptor()
	// placeholder.IDValidator is a validator for the "id" field. It is called by the builders before save.
	placeholder.IDValidator = placeholderDescID.Validators[0].(func(int64) error)
}
